<a href="https://colab.research.google.com/github/yadavshubham8871-afk/Pandas/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
print("Pandas imported successfully")

Pandas imported successfully

In [ ]:
student_names=["Amit","Priya","Rahul","Sneha"]
marks=[85,92,67,78]
avg_marks=sum(marks)/len(marks)
print("Average=",avg_marks)

Average= 80.5

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
students=pd.DataFrame({
"Name":["Amit","Atmiya","Aman","Kuldeep"],
"Marks":[85,92,67,78]
})
print(students)
students

      Name  Marks
0     Amit     85
1   Atmiya     92
2     Aman     67
3  Kuldeep     78

      Name  Marks
0     Amit     85
1   Atmiya     92
2     Aman     67
3  Kuldeep     78

In [ ]:
marks=pd.Series([85,92,67,78,90])
print(marks)

0    85
1    92
2    67
3    78
4    90
dtype: int64

In [ ]:
temperature=pd.Series([30,32,31,29,35,34,33])
print(temperature.mean())
print(temperature.max())
print(temperature.max())

32.0
35
35

In [ ]:
len(temperature)

7

In [ ]:
string=pd.Series(["Amit","Nikhil","Satyam"])
print(string)

0      Amit
1    Nikhil
2    Satyam
dtype: object

In [ ]:
series=pd.Series(["Amit",85,95.4,"Mohan"])
print(series)

0     Amit
1       85
2     95.4
3    Mohan
dtype: object

In [ ]:
data=pd.Series(
    [100,200,300,400,500],
    index=["Jan","Feb","Mar","Apr","May"]
  )
print(data)
print(data["Jan"])

Jan    100
Feb    200
Mar    300
Apr    400
May    500
dtype: int64
100

In [ ]:
print((data["Jan"]*100)/data.sum())

6.666666666666667

In [ ]:
data=pd.Series([100,150,145,120,135],
               index=["Python","SQL","Math","DAA","AI"])
print(data)

Python    100
SQL       150
Math      145
DAA       120
AI        135
dtype: int64

In [ ]:
s={"Python":100,
   "SQL":150,
   "Math":145,
   "DAA":120,
   "AI":135
  }
data=pd.Series(s)
print(data)

Python    100
SQL       150
Math      145
DAA       120
AI        135
dtype: int64

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
data=pd.Series(arr)
print(data)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
#write a code to create a numpy array of marks (out of 100) and then assign 10 bonus marks to each.
marks = np.array([95, 80, 90, 40, 50])
n_marks = marks+10
print(n_marks)

[105  90 100  50  60]

In [ ]:
n_marks=np.minimum(marks+10,100)
n_marks

array([100,  90, 100,  50,  60])

In [ ]:
marks=pd.Series([60,70,80,90])
marks+5

0    65
1    75
2    85
3    95
dtype: int64