<a href="https://colab.research.google.com/github/yadavshubham8871-afk/Pandas/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np
print("Pandas imported successfully")

Pandas imported successfully

In [51]:
data = {
"Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan",
"Neha", "Rohit", "Pooja", "Arjun", "Meera"],
"Age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18],
"Marks": [78, 92, 65, 88, 45, 95, 56, 72, 81, 69],
"Attendance": [85, 95, 70, 90, 60, 98, 75, 82, 88, 68],
"Branch": ["CSE", "ECE", "CSE", "IT", "ME",
"CSE", "ECE", "IT", "ME", "CSE"]
}
df=pd.DataFrame(data)

In [52]:
df.head()
df.head(3)
df.tail()
df.tail(3)

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [53]:
df.sample()

  Student  Age  Marks  Attendance Branch
5    Neha   18     95          98    CSE

In [54]:
df.sample()

  Student  Age  Marks  Attendance Branch
2   Rahul   18     65          70    CSE

In [55]:
df.sample()

  Student  Age  Marks  Attendance Branch
1   Priya   19     92          95    ECE

In [56]:
df.sample(3)

  Student  Age  Marks  Attendance Branch
3   Sneha   20     88          90     IT
9   Meera   18     69          68    CSE
8   Arjun   20     81          88     ME

In [57]:
df.sample(3, random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [58]:
df.sample(3, random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [59]:
large_df = pd.DataFrame({
"Employee_ID": range(1001, 1021),
"Salary": [
25000, 30000, 28000, 45000, 50000,
32000, 38000, 41000, 29000, 60000,
35000, 48000, 52000, 27000, 39000,
43000, 31000, 55000, 36000, 47000
]
})
large_df

    Employee_ID  Salary
0          1001   25000
1          1002   30000
2          1003   28000
3          1004   45000
4          1005   50000
5          1006   32000
6          1007   38000
7          1008   41000
8          1009   29000
9          1010   60000
10         1011   35000
11         1012   48000
12         1013   52000
13         1014   27000
14         1015   39000
15         1016   43000
16         1017   31000
17         1018   55000
18         1019   36000
19         1020   47000

In [60]:
large_df.sample(5,random_state=30)

    Employee_ID  Salary
11         1012   48000
0          1001   25000
15         1016   43000
14         1015   39000
9          1010   60000

In [61]:
large_df.sample(5,random_state=30)

    Employee_ID  Salary
11         1012   48000
0          1001   25000
15         1016   43000
14         1015   39000
9          1010   60000

In [62]:
df.shape  #it is not a function call so bracket is remove

(10, 5)

In [63]:
row,col=df.shape
row

10

In [64]:
col

5

In [65]:
df.size

50

In [66]:
#Check whether dataset has any record
if df.shape[0]>0:
  print("dataset contains record")
else:
  print("dataset not contains record")

dataset contains record

In [67]:
#Creating an empty dataframe
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [68]:
df=pd.DataFrame(data)
df

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [70]:
#Extract all column
df.columns

Index(['Student', 'Age', 'Marks', 'Attendance', 'Branch'], dtype='object')

In [ ]:
# #check if a specific column exists in the dataframe?
# c=input()
# if c in col:
#    print("Column Found")
# else:
#   print("Column Not found")

In [ ]:
df1 = pd.DataFrame({
"Employee_ID": range(1001, 1006),
"Salary": [
25000, 30000, 28000, 45000, 50000
]
})
df1

In [ ]:
c=list(df1.columns)
print(c)

In [ ]:
c[0]="Student ID"
print(c)

In [ ]:
df1.columns=["Student ID","Salary"]
df1.columns

In [ ]:
# Find the Product of All Elements Except the Current Element
# Problem statement: Create a result array in which each position contains
# the product of all the other array elements, without dividing by the current element.
# Example: [1, 2, 3, 4]
# Output: [24, 12, 8, 6]
# logic:
# pick an elem:
# inner loop: find product of all , but skip that elem using index.

arr=[1,2,3,4]
pro=[]
for i in range(len(arr)):
  p=1
  for j in range(len(arr)):
    if i!=j:
      p*=arr[j]
  pro.append(p)
print(pro)

In [ ]:
# Left Rotate an Array by One Position
# Problem statement:
# Given an array, rotate all elements one position to the left.
# The first element should move to the last position.
# Example: [10, 20, 30, 40, 50]
# Output: [20, 30, 40, 50, 10]
list= [10, 20, 30, 40, 50]
n=len(list)
l=[]
for i in range(n-1):
  list[i]=list[i+1]
print(list)

In [ ]:
list= [10, 20, 30, 40, 50]
ans=list[1:]+list[:1]
ans

In [ ]:
# Right Rotate an Array by K Positions
# Problem statement: Rotate an array to the right by k positions.
# Example: [1, 2, 3, 4, 5], k = 2
# Output: [4, 5, 1, 2, 3]

l=[1,2,3,4,5,6]
k=int(input())
a=l[k+1:]
b=l[:k+1]
print(a+b)

In [80]:
# Find the Intersection Without Duplicates
# Problem statement: Print distinct elements common to both arrays,
# even if an element appears multiple times in either input

# Example: [2,2,4,6,6,8] and [2,6,6,10]
# ans: [2,6]

a=[2,2,4,6,6,8]
b=[2,6,6,10]
c=[]
d=[]
for i in a:
  if i in (a and b) and i not in c:
    c.append(i)
print(c)

[2, 6]

In [76]:
# Find the Union of Two Arrays
# Problem statement: Print every distinct element that appears in either of two arrays.
# Do not print duplicates.
a = [1, 2, 3, 4]
b = [3, 4, 5, 6]
# ans = [1,2,3,4,5,6]

a = [1, 2, 3, 4]
b = [3, 4, 5, 6]
c=a+b
print(c)
d=[]
for i in c:
  if i not in d:
    d.append(i)
print(d)

[1, 2, 3, 4, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]