<a href="https://colab.research.google.com/github/yadavshubham8871-afk/Pandas/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
print("Pandas imported successfully")

Pandas imported successfully

In [ ]:
data = {
"Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan",
"Neha", "Rohit", "Pooja", "Arjun", "Meera"],
"Age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18],
"Marks": [78, 92, 65, 88, 45, 95, 56, 72, 81, 69],
"Attendance": [85, 95, 70, 90, 60, 98, 75, 82, 88, 68],
"Branch": ["CSE", "ECE", "CSE", "IT", "ME",
"CSE", "ECE", "IT", "ME", "CSE"]
}
df=pd.DataFrame(data)

In [ ]:
df.head()
df.head(3)
df.tail()
df.tail(3)

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [ ]:
df.sample()

  Student  Age  Marks  Attendance Branch
3   Sneha   20     88          90     IT

In [ ]:
df.sample()

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT

In [ ]:
df.sample()

  Student  Age  Marks  Attendance Branch
2   Rahul   18     65          70    CSE

In [ ]:
df.sample(3)

  Student  Age  Marks  Attendance Branch
5    Neha   18     95          98    CSE
1   Priya   19     92          95    ECE
4   Karan   19     45          60     ME